name: Build Docker Images

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build-push-images:
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare build args
        id: build_args
        run: |
          github_sha_short=${GITHUB_SHA:0:7}
          push=${{ github.event_name == 'push' && !env.ACT }}
          echo "::set-output name=commit_sha_short::$github_sha_short"
          echo "::set-output name=image_tag::sha-$github_sha_short"
          echo "::set-output name=push::$push"

### BUILD & PUSH SERVER IMAGE ###

      - name: Metatags for the Server image
        id: meta_server
        uses: docker/metadata-action@v3
        with:
          images: temporaliotest/server
          tags: |
            type=sha,format=short,event=branch
            latest

      - name: Build-Push Server image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ steps.build_args.outputs.push }}
          file: server.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_server.outputs.tags }}
          labels: ${{ steps.meta_server.outputs.labels }}

      - name: Run Trivy vulnerability scanner on Server image
        uses: ./.github/actions/trivy
        with:
          image-tags: ${{ steps.meta_server.outputs.tags }}
          image-name: server

### BUILD & PUSH ADMIN TOOLS IMAGE ###

      - name: Metatags for the Admin Tools image
        if: steps.build_args.outputs.push == 'true'
        id: meta_admin_tools
        uses: docker/metadata-action@v3
        with:
          images: temporaliotest/admin-tools
          tags: |
            type=sha,format=short,event=branch
            latest

      - name: Build-Push Admin Tools
        if: steps.build_args.outputs.push == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ steps.build_args.outputs.push }}
          file: admin-tools.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_admin_tools.outputs.tags }}
          labels: ${{ steps.meta_admin_tools.outputs.labels }}
          build-args: |
            SERVER_IMAGE=temporaliotest/server:${{ steps.build_args.outputs.image_tag }}

      - name: Run Trivy vulnerability scanner on Admin Tools image
        if: steps.build_args.outputs.push == 'true'
        uses: ./.github/actions/trivy
        with:
          image-tags: ${{ steps.meta_admin_tools.outputs.tags }}
          image-name: admin-tools

      - name: Dispatch CICD
        if: steps.build_args.outputs.push == 'true'
        env:
          PAT: ${{ secrets.COMMANDER_DATA_TOKEN }}
          PARENT_REPO: temporalio/cicd-builds
          WORKFLOW_ID: publish-stage-results.yml
          PARENT_BRANCH: ${{ toJSON('master') }}
          STAGE: ${{ toJSON('builds') }}
          COMPONENT: ${{ toJSON('temporal') }}
          TAG: ${{ steps.build_args.outputs.image_tag }}
          AUTHOR: ${{ toJSON(github.event.head_commit.author.name) }}
          COMMIT_MESSAGE: ${{ toJSON(github.event.head_commit.message) }}
        run: |
          curl -fL -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $PAT" "https://api.github.com/repos/$PARENT_REPO/actions/workflows/$WORKFLOW_ID/dispatches" -d '{"ref":'"$PARENT_BRANCH"', "inputs": { "stage":'"$STAGE"', "component":'"$COMPONENT"', "image_tag":"'"$TAG"'", "commit_author":'"$AUTHOR"', "commit_message":'"$COMMIT_MESSAGE"' }}'

### BUILD & PUSH AUTO SETUP IMAGE ###

      - name: Metatags for the Auto Setup image
        if: steps.build_args.outputs.push == 'true'
        id: meta_auto_setup
        uses: docker/metadata-action@v3
        with:
          images: temporaliotest/auto-setup
          tags: |
            type=sha,format=short,event=branch
            latest

      - name: Build-Push Auto Setup
        if: steps.build_args.outputs.push == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ steps.build_args.outputs.push }}
          file: auto-setup.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_auto_setup.outputs.tags }}
          labels: ${{ steps.meta_auto_setup.outputs.labels }}
          build-args: |
            SERVER_IMAGE=temporaliotest/server:${{ steps.build_args.outputs.image_tag }}
            ADMIN_TOOLS_IMAGE=temporaliotest/admin-tools:${{ steps.build_args.outputs.image_tag }}

      - name: Run Trivy vulnerability scanner on Auto Setup image
        if: steps.build_args.outputs.push == 'true'
        uses: ./.github/actions/trivy
        with:
          image-tags: ${{ steps.meta_auto_setup.outputs.tags }}
          image-name: auto-setup
