name: Publish Temporal server image

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  publish_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Docker build-args
        id: build_args
        run: |
          echo "::set-output name=github_sha_short::$(echo $GITHUB_SHA | cut -c 1-7)"

      - name: Docker meta for Commit image
        id: meta_commit
        uses: docker/metadata-action@v3
        if: github.event_name == 'push'
        with:
          images: temporaliotest/server
          tags: |
            type=sha,format=short,event=branch

      - name: Push Commit image to DockerHub
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          file: server.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_commit.outputs.tags }}
          labels: ${{ steps.meta_commit.outputs.labels }}
          build-args: |
            GITHUB_SHA_SHORT=${{ steps.build_args.outputs.github_sha_short }}

      - name: Dispatch Commit image CICD
        if: github.event_name == 'push'
        env:
          PAT: ${{ secrets.COMMANDER_DATA_TOKEN }}
          PARENT_REPO: temporalio/cicd-builds
          PARENT_BRANCH: master
          WORKFLOW_ID: publish-stage-results.yml
          STAGE: builds
          COMPONENT: temporal
          TAG: sha-${{ steps.build_args.outputs.github_sha_short }}
          AUTHOR: ${{ github.event.pusher.name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl -fL -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.PAT }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}", "inputs": { "stage":"${{ env.STAGE }}", "component":"${{ env.COMPONENT }}", "image_tag":"${{ env.TAG }}", "commit_author":"${{ env.AUTHOR }}", "commit_message":"${{ env.COMMIT_MESSAGE }}" }}'

      - name: Docker meta for Release image
        id: meta_release
        uses: docker/metadata-action@v3
        if: github.event_name == 'release'
        with:
          images: temporalio/server
          tags: |
            type=semver,pattern={{version}}

      - name: Push Release image to DockerHub
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          push: true
          file: server.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_release.outputs.tags }}
          labels: ${{ steps.meta_release.outputs.labels }}
          build-args: |
            GITHUB_SHA_SHORT=${{ steps.build_args.outputs.github_sha_short }}
