name: Release Admin Tools Image

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Repo Commit sha"
        required: true
      patch:
        description: "The optional patch version of the admintools image"
        required: false
      latest:
        type: boolean
        description: "Also update latest tag"
        required: true
        default: false
      major:
        type: boolean
        description: "Also update major tag"
        required: true
        default: false
      dry-run:
        description: "Whether or not this is a dry run"
        type: boolean
        required: false
        default: true

jobs:
  release-admin-tools:
    name: "Re-tag and release images"
    runs-on: ubuntu-latest

    steps:
      # Main
      - uses: actions/checkout@v4
      # For the action itself
      - uses: actions/checkout@v4
        with:
          path: target
          submodules: "true"
          ref: ${{ github.event.inputs.commit }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - name: Calculate admintools tag
        run: |
          today=$(date "+%Y.%-m.%-d" | tr -d '\n')
          patch=
          if [ -n "${{inputs.patch}}" ]; then
            patch="-p${{inputs.patch}}"
          fi
          temporal_ver=$(cd target/temporal && git describe --tags | cut -d '-' -f-2)
          cli_ver=$(cd target/cli && git describe --tags | cut -d '-' -f-2)
          tctl_ver=$(cd target/tctl && git describe --tags | cut -d '-' -f-2)
          echo "TAG=${today}${patch}+server-${temporal_ver}.cli-${cli_ver}.tctl-${tctl_ver}" >> "${GITHUB_ENV}"
      - name: Copy images
        env:
          COMMIT: ${{ github.event.inputs.commit }}
          TAG: ${{ env.TAG }}
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PAT }}
          IMAGES: admintools
          SRC_REPO: temporaliotest
          DST_REPO: temporalio
          LATEST: ${{ github.event.inputs.latest }}
          MAJOR: ${{ github.event.inputs.major }}
        run: go run src/release_temporal/main.go
