name: Release Admin Tools Image

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Repo Commit sha"
        required: true
      patch:
        description: "The optional patch version of the admintools image"
        required: false
      latest:
        type: boolean
        description: "Also update latest tag"
        required: true
        default: false
      major:
        type: boolean
        description: "Also update major tag"
        required: true
        default: false
      dry-run:
        description: "Whether or not this is a dry run"
        type: boolean
        required: false
        default: true

jobs:
  retag-and-release:
    name: "Re-tag and release images"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "**/go.mod"
      - name: Calculate admintools tag
        run: |
            today=$(date "+%Y.%m.%d" | tr -d '\n')
            patch=
            if [ -n "${{inputs.patch}}" ]; then
               patch="_${{inputs.patch}}"
            fi
            temporal_sha=$(shell sh -c 'git submodule status -- temporal | cut -c2-40')
            cli_sha=$(shell sh -c 'git submodule status -- cli | cut -c2-40')
            echo "TAG=${today}${patch}+server-${temporal_sha}-cli-${cli_sha}" >> "${GITHUB_ENV}"
      - name: Copy images
        if: ! ${{ inputs.dry-run }}
        env:
          COMMIT: ${{ github.event.inputs.commit }}
          TAG: ${{ env.TAG }}
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PAT }}
          IMAGES: admintools
          SRC_REPO: temporaliotest
          DST_REPO: temporalio
          LATEST: ${{ github.event.inputs.latest }}
          MAJOR: ${{ github.event.inputs.major }}
        run: go run src/release_temporal/main.go
