name: Release All Base Docker images

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit sha to build from"
        default: '$GITHUB_SHA'
        required: true
      tag:
        description: "New tag for the image"
        default: test
        required: true

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
        image: [base-server, base-builder, base-admin-tools, base-ci-builder]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Metatags for the image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: temporalio/${{ matrix.image }}
          tags: ${{ github.event.inputs.tag }}

      - name: Build-Push Base-* image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/base-images/${{ matrix.image }}.Dockerfile
          platforms: ${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
